name: Packages

on: workflow_dispatch

jobs:
  get-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - run: |
          gh api --jq '.[] | select(.repository.name == "frontend-apps") | .name' \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            '/orgs/simmcomm/packages?package_type=container'
